### PR TITLE
Adds support for timestamps submitted as floats

### LINKED ISSUE #26: Support for timestamps submitted as floats
From Dylan:
"
Currently, if someone using the Python library (and potentially other libraries) tries to send in a float as a timestamp, it gets converted to something like 1426982400.0. This doesn't generate any errors, and it shows up in the live tab just fine, but any events recorded with this timestamp won't be properly processed and won't show up in a user's account.
"

### PR DESCRIPTION
**Pull request by supernullset**
Closes #26

Adds support for recording events with float timestamps, which is happening from time to time. See issue for details.

### CODE REVIEW

**Comment by njm** [comment]
This misses timestamps for property assignment via `set()`.  Perhaps a better place to apply the conversion might be in [`create_query()`][1]?

[1]: https://github.com/kissmetrics/py-KISSmetrics/blob/sjw/floats-to-ints/KISSmetrics/query_string.py#L44-L46

**Comment by supernullset** [comment]
Mayhaps! I will investigate

**Comment by supernullset** [comment]
Good call Nick; much more targeted solution, thanks for pointing it out

**Comment by ewdurbin** [comment]
:+1:

**Comment by ewdurbin** [comment]
thanks @supernullset i'll get a 1.0.1 release out

**Pull request merged**
